server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: masterChief-users
          uri: lb://users
          order: 0
          predicates:
            - Path=/users/**
        - id: masterChief-race
          uri: lb://race
          order: 0
          predicates:
            - Path=/race/**
        - id: masterChief-manager
          uri: lb://manager
          order: 0
          predicates:
            - Path=/manager/**
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

time:
  nacos:
    gateway:
      address: 127.0.0.1:8848
      dataId: real-estate-manager-dev.yaml
      groupId: DEFAULT_GROUP
      timeout: 5000
